### ISSUE TITLE
Share publicly

### ISSUE THREAD

**Issue by planemad** [stopcoronatn/stopcoronatn.github.io#1]
Fantastic work @pratapvardhan @devdattaT for putting things together so quickly 🙏 ❤️ 

https://stopcoronatn.github.io looks ready to share. Anything we should add before sharing publicly?

**Comment by pratapvardhan** [comment]
@planemad -- should we update the readme to make it more explicit, that this is private hospitals data only?

**Comment by planemad** [comment]
@pratapvardhan Good call, done.
